### PR TITLE
1.19.2

### PR DESCRIPTION
**Pull request by czruby**

### CODE REVIEW

**Comment by AnzhiZhang** [comment]
感谢，已打包上传，还请帮忙测试一下
https://www.curseforge.com/minecraft/mc-mods/mcdr-command-fabric/files/4344475

**Comment by czruby** [comment]
在我的1.19.2服务器上测试，运行正常

**Comment by Adogs1** [comment]
> 在我的1.19.2服务器上测试，运行正常

How can I add 1.20.2 support?

**Comment by czruby** [comment]
> > 在我的1.19.2服务器上测试，运行正常
> 
> How can I add 1.20.2 support?

Maybe you can clone the repository to local, and modify the build properties. Then build the mod and see whether there is any old API function to be changed.

**Comment by Adogs1** [comment]
> > > 在我的1.19.2服务器上测试，运行正常
> > 
> > 
> > 如何添加 1.20.2 支持？
> 
> 也许您可以将存储库克隆到本地，并修改构建属性。然后构建 mod，看看是否有任何旧的 API 函数需要更改。

Okay, I've tried many times and it all failed.I am still looking forward to the author's updates after 1.21

**Comment by czruby** [comment]
> > > > 在我的1.19.2服务器上测试，运行正常
> > > 
> > > 
> > > 如何添加 1.20.2 支持？
> > 
> > 
> > 也许您可以将存储库克隆到本地，并修改构建属性。然后构建 mod，看看是否有任何旧的 API 函数需要更改。
> 
> Okay, I've tried many times and it all failed.I am still looking forward to the author's updates after 1.21

Where have you failed to build the mod? You can add some details so that probably I can help you fix it.

**Pull request merged**
